# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_event_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'slika', 'verbose_name_plural': 'slike'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='img',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to='static/img'),
        ),
    ]
