# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_remove_userprofile_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(db_index=True, max_length=15, null=True, unique=True, verbose_name='Token'),
        ),
    ]
