# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_auto_20170422_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
