# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Ime'),
        ),
    ]
