# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0009_auto_20170425_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='img',
            new_name='img_event',
        ),
    ]
