# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_auto_20170425_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='btn_type',
            field=models.CharField(default='Kupi karto', max_length=30, verbose_name='Napis na gumbu'),
        ),
    ]
