# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0011_event_btn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='btn_type',
            field=models.CharField(max_length=30, verbose_name='Napis na gumbu'),
        ),
    ]
