# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0013_auto_20170425_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(max_length=30, null=True, verbose_name='kratek opis'),
        ),
    ]
