# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0014_event_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='btn_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='img_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Slika'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
