# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0028_auto_20170404_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='for_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pro.Product', verbose_name='Za izdelek'),
        ),
    ]
